'use strict';

/**
 * oversightNotifier — one notice to the central oversight inbox (info@advantage.bid) per campaign reply
 * that a person should see, with the reply text, the campaign, the company and what was done.
 *
 * Deliberately quiet: out-of-office replies, bounces and duplicates never notify (they are recorded and
 * handled automatically). Every notice is sent at most once (the caller holds inbound_email_receipts.notified_at).
 *
 * Deliberately careful with content:
 *   - only the new part of the reply: quoted history ("On ... wrote:", "> ...") is removed, which also
 *     removes our own claim and unsubscribe links that a reply quotes back;
 *   - card-number-like and SSN-like sequences are masked; remaining claim / unsubscribe links are removed;
 *   - capped at 2,000 characters; no attachments; plain text plus escaped HTML;
 *   - marked Auto-Submitted and X-Advantage-Oversight, so auto-responders do not answer it and the inbound
 *     pipeline ignores it if it ever comes back.
 */

const TOOLBOX = {
  claimed_listing: 'https://bid.advantage.bid/admin/sales.html',
  event_partner: 'https://bid.advantage.bid/admin/event-partners.html',
  unmatched: 'https://bid.advantage.bid/admin/sales.html',
};
const LABEL = { claimed_listing: 'Claimed Listing outreach', event_partner: 'Event Partner outreach', unmatched: 'No campaign matched' };
const MAX_TEXT = 2000;

const SILENT = new Set(['OUT_OF_OFFICE', 'HARD_BOUNCE', 'SOFT_BOUNCE']);
const SILENT_ACTIONS = new Set(['ignored_auto_reply', 'recorded_soft_bounce', 'suppressed_hard_bounce']);

/** Should this processed reply produce a notice, and of which kind? */
function decide(outcome) {
  if (!outcome || outcome.duplicate) return { notify: false, kind: null };
  if (SILENT.has(outcome.classification) || SILENT_ACTIONS.has(outcome.action)) return { notify: false, kind: null };
  if (outcome.classification === 'STOP_UNSUBSCRIBE') return { notify: true, kind: 'opt_out' };
  if (outcome.classification === 'LEGAL_RIGHTS' || outcome.action === 'escalated_legal') return { notify: true, kind: 'legal' };
  return { notify: true, kind: 'reply' };
}

/** The new part of a reply only, with sensitive sequences masked. */
function safeExcerpt(text) {
  const lines = String(text || '').replace(/\r\n/g, '\n').split('\n');
  const out = [];
  for (const line of lines) {
    if (/^\s*On .+wrote:\s*$/i.test(line) || /^-{2,}\s*Original Message\s*-{2,}/i.test(line) || /^\s*From:\s.+@/i.test(line)) break;
    if (/^\s*>/.test(line)) continue;
    out.push(line);
  }
  let s = out.join('\n').trim();
  s = s.replace(/\b(?:\d[ -]?){13,19}\b/g, '[number removed]')
    .replace(/\b\d{3}-\d{2}-\d{4}\b/g, '[number removed]')
    .replace(/https?:\/\/\S*(?:\/claim\/|unsubscribe\?t=|[?&]token=)\S*/gi, '[link removed]');
  if (s.length > MAX_TEXT) s = s.slice(0, MAX_TEXT) + '\n[... shortened]';
  return s || '(no text)';
}

const HEADLINE = {
  reply: 'Reply needs a person',
  legal: 'LEGAL or rights concern: escalated to the Owner',
  opt_out: 'Opt-out processed automatically',
  needs_review: 'Held for review',
  quarantined: 'Blocked by the attachment scan',
  failed: 'Could not be processed',
};
const HANDLING = {
  reply: 'Automation for this company stopped; a task was opened. Please answer personally within one business day.',
  legal: 'Automation stopped and the reply was escalated. The Owner should review it before anyone answers.',
  opt_out: 'The address was suppressed across campaigns and the sequence stopped. No action needed.',
};

function compose(input) {
  const kind = input.kind || 'reply';
  const programme = input.programme || 'unmatched';
  const n = input.normalized || {};
  const company = input.company || null;
  const from = n.fromEmail || input.fromEmail || 'unknown sender';
  const subject = '[' + LABEL[programme] + '] ' + HEADLINE[kind] + (company ? ': ' + company : '');
  const rows = [
    ['Campaign', LABEL[programme]],
    ['Company', company || 'Not matched'],
    ['From', (n.fromName ? n.fromName + ' ' : '') + '<' + from + '>'],
    ['Subject', n.subject || '(none)'],
    ['Classified as', input.classification || '(not classified)'],
    ['Handling', HANDLING[kind] || input.reason || ''],
    ['Review', TOOLBOX[programme]],
    ['Reference', String(input.receiptId || '')],
  ];
  const body = n.textBody !== undefined && kind !== 'quarantined' && kind !== 'failed' ? safeExcerpt(n.textBody) : null;
  const text = rows.map(([k, v]) => k + ': ' + v).join('\n')
    + (body ? '\n\nMessage:\n' + body : '')
    + '\n\nThis notice was generated by the Advantage.Bid inbound system. Please do not reply to it; answer the company from the review page or your own mailbox.';
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const html = '<table style="font-family:Arial,sans-serif;font-size:14px;border-collapse:collapse">'
    + rows.map(([k, v]) => '<tr><td style="padding:4px 12px 4px 0;color:#555;vertical-align:top"><b>' + esc(k) + '</b></td><td style="padding:4px 0">' + esc(v) + '</td></tr>').join('')
    + '</table>' + (body ? '<p style="font-family:Arial,sans-serif;font-size:14px"><b>Message</b></p><pre style="white-space:pre-wrap;font-family:Arial,sans-serif;font-size:14px;background:#f5f7fa;padding:12px">' + esc(body) + '</pre>' : '')
    + '<p style="font-family:Arial,sans-serif;font-size:12px;color:#666">Generated by the Advantage.Bid inbound system. Please do not reply to this notice.</p>';
  return { subject: subject.slice(0, 200), text, html };
}

async function notify(input, deps = {}) {
  const emailService = deps.emailService || require('../emailService');
  const msg = compose(input);
  return emailService.sendEmail({
    to: process.env.INBOUND_OVERSIGHT_EMAIL || 'info@advantage.bid',
    subject: msg.subject, text: msg.text, html: msg.html,
    headers: { 'Auto-Submitted': 'auto-generated', 'X-Advantage-Oversight': '1' },
  });
}

module.exports = { decide, safeExcerpt, compose, notify, LABEL };
